const LIST_CHECKBOX = [
    { id: 1, contentLabel: "Thẻ" },
    { id: 2, contentLabel: "Xưng hô" },
    { id: 3, contentLabel: "Họ và tên" },
    { id: 4, contentLabel: "Chức danh" },
    { id: 5, contentLabel: "ĐT di động" },
    { id: 6, contentLabel: "ĐT cơ quan" },
    { id: 7, contentLabel: "Email cơ quan" },
    { id: 8, contentLabel: "Email cá nhân" },
    { id: 9, contentLabel: "Tổ chức" },
    { id: 10, contentLabel: "Địa chỉ" },
    { id: 11, contentLabel: "Tỉnh/thành phố" },
    { id: 12, contentLabel: "Quận/huyện" },
    { id: 13, contentLabel: "Phường/Xã" },
    { id: 14, contentLabel: "Nguồn gốc" },
    { id: 15, contentLabel: "Loại hình" },
    { id: 16, contentLabel: "Lĩnh vực" },
    { id: 17, contentLabel: "Mô tả" },
]
export default LIST_CHECKBOX